package com.jobskills.model.enums;

public enum BusinessType {
    RETAIL_STORE, RESTAURANT_FOOD_SERVICE, HOSPITALITY, OFFICE_ADMINISTRATION,
    HEALTHCARE, EDUCATION, CONSTRUCTION, AGRICULTURE, FISHERIES, MANUFACTURING,
    LOGISTICS_DELIVERY, TRANSPORTATION, AUTOMOTIVE, SECURITY, IT_TECHNOLOGY, OTHER
}