package com.jobskills.model.enums;

public enum JobCategory {
    RETAIL_STORE, SALES, FOOD_SERVICE_RESTAURANT, HOSPITALITY_TOURISM,
    OFFICE_ADMINISTRATION, ACCOUNTING_FINANCE, HEALTHCARE, EDUCATION_TUTORING,
    CONSTRUCTION_SKILLED_TRADES, AGRICULTURE, FISHERIES, MANUFACTURING,
    LOGISTICS_DELIVERY, TRANSPORTATION, AUTOMOTIVE_MECHANICAL, CUSTOMER_SERVICE,
    SECURITY, GENERAL_LABOR, IT_TECHNOLOGY, OTHER
}